-- Eliminar paquetes y sus cuerpos
DROP PACKAGE BODY PKG_GESTION_ADMINISTRATIVA;
DROP PACKAGE PKG_GESTION_ADMINISTRATIVA;

DROP PACKAGE BODY PKG_REFERENCIAS;
DROP PACKAGE PKG_REFERENCIAS;

DROP PACKAGE BODY PKG_TARJETA_CREDITO;
DROP PACKAGE PKG_TARJETA_CREDITO;

DROP PACKAGE BODY PKG_CUENTA_BANCARIA;
DROP PACKAGE PKG_CUENTA_BANCARIA;

DROP PACKAGE BODY PKG_PRESTAMO;
DROP PACKAGE PKG_PRESTAMO;

DROP PACKAGE BODY PKG_SOLICITUD_PRESTAMO;
DROP PACKAGE PKG_SOLICITUD_PRESTAMO;

DROP PACKAGE BODY PKG_GESTION_PRESTAMO;
DROP PACKAGE PKG_GESTION_PRESTAMO;
