-- Eliminar tablas del modulo Solicitud
DROP TABLE EtapaFlujoAprobacion CASCADE CONSTRAINTS;
DROP TABLE FlujoAprobacion CASCADE CONSTRAINTS;
DROP TABLE Regla CASCADE CONSTRAINTS;
DROP TABLE Etapa CASCADE CONSTRAINTS;
DROP TABLE Adjunto CASCADE CONSTRAINTS;
DROP TABLE SolicitudPrestamo CASCADE CONSTRAINTS;
DROP TABLE TipoSolicitud CASCADE CONSTRAINTS;

-- Modulo Prestamo
DROP TABLE CobroPrestamo CASCADE CONSTRAINTS;
DROP TABLE PagoPrestamo CASCADE CONSTRAINTS;
DROP TABLE PrestamoTipoInteres CASCADE CONSTRAINTS;
DROP TABLE TipoInteres CASCADE CONSTRAINTS;
DROP TABLE Prestamo CASCADE CONSTRAINTS;
DROP TABLE TipoPrestamo CASCADE CONSTRAINTS;

-- Modulo Cuenta
DROP TABLE Transaccion CASCADE CONSTRAINTS;
DROP TABLE TipoTransaccion CASCADE CONSTRAINTS;
DROP TABLE TarjetaDebito CASCADE CONSTRAINTS;
DROP TABLE Cuenta CASCADE CONSTRAINTS;
DROP TABLE TipoCuenta CASCADE CONSTRAINTS;

-- Modulo Tarjeta
DROP TABLE CorteMoneda CASCADE CONSTRAINTS;
DROP TABLE Moneda CASCADE CONSTRAINTS;
DROP TABLE Corte CASCADE CONSTRAINTS;
DROP TABLE TarjetaRubro CASCADE CONSTRAINTS;
DROP TABLE Rubro CASCADE CONSTRAINTS;
DROP TABLE Movimiento CASCADE CONSTRAINTS;
DROP TABLE TipoMovimiento CASCADE CONSTRAINTS;
DROP TABLE TarjetaCredito CASCADE CONSTRAINTS;
DROP TABLE TipoTarjeta CASCADE CONSTRAINTS;

-- Modulo Referencias
DROP TABLE ClienteReferencia CASCADE CONSTRAINTS;
DROP TABLE Referencias CASCADE CONSTRAINTS;

-- Modulo Gestion Administrativa
DROP TABLE Cliente CASCADE CONSTRAINTS;
DROP TABLE EmpleadoCargo CASCADE CONSTRAINTS;
DROP TABLE Cargo CASCADE CONSTRAINTS;
DROP TABLE Empleado CASCADE CONSTRAINTS;
DROP TABLE Telefono CASCADE CONSTRAINTS;
DROP TABLE Persona CASCADE CONSTRAINTS;
DROP TABLE Sucursal CASCADE CONSTRAINTS;
DROP TABLE Banco CASCADE CONSTRAINTS;
